### ISSUE TITLE
Scraper Requests

### ISSUE THREAD

**Issue by toprak** [AdollaApp/Adolla#15]
- https://toonily.com/ for korean stuff it is really nice
- ~~https://manganelo.com/~~ nice for some mangas that can not be found on mangasee and mangadex
~~https://nhentai.com we talked about it with you if its hard do not add it :D~~

**Comment by JipFr** [comment]
One of these scrapers has been added.... if you catch my drift.

**Comment by toprak** [comment]
sooo, I can continue to my perv stuff on adolla :D

**Comment by JipFr** [comment]
I attempted making a manganelo scraper, but as it turns out they protect their images through CloudFlare. I'm not sure how to bypass that.

**Comment by JipFr** [comment]
Manganelo has been added as a scraper!
