### ISSUE TITLE
Add support for local* reading

### ISSUE THREAD

**Issue by farahnur42** [AdollaApp/Adolla#16]
Hi, I found this repository while somewhat mindlessly browsing for manga readers a while back, and found it to be quite quaint for what seemed like a very new project and rather well-fleshed out (especially the reader). However there is one major barrier for *me* at least which is the lack of offline reading capabilities (to be clear I'm specifically talking about being able to read locally stored files with customizable library path and *not* the way Tachiyomi handles it for the most part which is grabbing chapters from the various sites and storing them in their own library format in a fixed location) whatsoever so I was wondering if it was possible to add that functionality to this.

 [Another minor-ish nitpick I had* at the time is the inability to make the non-reader bars disappear but that we can postpone for later] 
 
Cheers.

**Comment by JipFr** [comment]
> found it to be quite quaint for what seemed like a very new project and rather well-fleshed out (especially the reader).

Thank you!

> However there is one major barrier for me at least which is the lack of offline reading capabilities (to be clear I'm specifically talking about being able to read locally stored files with customizable library path and not the way Tachiyomi handles it for the most part which is grabbing chapters from the various sites and storing them in their own library format in a fixed location) whatsoever so I was wondering if it was possible to add that functionality to this.

I'm afraid I've never actually used Tachiyomi myself, so I'm not familiar with how they do it. You mention local files, but sadly that's not possible with web technologies. There is the file system access API (https://web.dev/file-system-access/) though that's very new and not widely supported yet. 

Could you clarify what you meant?

> [Another minor-ish nitpick I had* at the time is the inability to make the non-reader bars disappear but that we can postpone for later]

How do you mean? As far as I'm aware, every bar can be removed.
![IMG_7D840D64C029-1](https://user-images.githubusercontent.com/17685409/104121068-e714ad80-533b-11eb-8ca6-8889364e9107.jpeg)

**Comment by toprak** [comment]
Fahim, you again :D

**Comment by farahnur42** [comment]
> I'm afraid I've never actually used Tachiyomi myself, so I'm not familiar with how they do it. You mention local files, but sadly that's not possible with web technologies. There is the file system access API (https://web.dev/file-system-access/) though that's very new and not widely supported yet.
> 
> Could you clarify what you meant?

@JipFr Just thought up an alternative theoretical solution to this issue, adding Komga as a source ([Komga](https://github.com/gotson/komga) is a self-hosted media server for comics and manga, there's an official [Tachiyomi extension](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/komga) by the Komga dev that you can look at for how they've done or get *some* idea about it at least). This way you wouldn't have to worry about local library/file handling and etc and just let Komga handle it. 

As for
> How do you mean? As far as I'm aware, every bar can be removed.

I meant the side bar that isn't part of the reader itself and not any bars inside the reader.
![image](https://user-images.githubusercontent.com/37258115/104139573-c5b4cf80-53d6-11eb-87cf-3c4a1db7cbd5.png)




> Fahim, you again :D

@toprak Didn't know your github username, Fuchisa (I assume you're Fuchisa, since everything else checks out :D)

**Comment by toprak** [comment]
@farahnur42 yeah mate :D

**Comment by JipFr** [comment]
So the way I understand it is, you don't want "offline reading", but you want the ability to read local files (either from Komga or a local file structure)?

**Comment by toprak** [comment]
Is not reading local files already offline reading?

**Comment by JipFr** [comment]
The Adolla server is often in a different location than the device you're reading on, so "local" in this case would be on the Adolla server

**Comment by farahnur42** [comment]
> So the way I understand it is, you don't want "offline reading", but you want the ability to read local files (either from Komga or a local file structure)?

Aye, that's it.

**Comment by JipFr** [comment]
Admittedly late but I forgot to mention this here before: 

> I meant the side bar that isn't part of the reader itself and not any bars inside the reader.

This can now be hidden if you click the images on desktop, also works on tablet

**Comment by farahnur42** [comment]
@JipFr I haven't touched Adolla in a few months anyways cos I got the AMR dev to add Komga support to [AMR](https://gitlab.com/all-mangas-reader/all-mangas-reader-2) so I've just been using that, but good to know.

**Comment by JipFr** [comment]
Update: this will not be added unless there is more demand for it in the future, which I can't imagine because the app doesn't have offline use anyways.
