### ISSUE TITLE
Add dual pages in manga reader view

### ISSUE THREAD

**Issue by yash-278** [AdollaApp/Adolla#22]
Hi, Is it possible to add like 2 images in reader view ? Since on Desktop version there's much space for dual images. I think it might be a good QOL enhancement.

**Comment by JipFr** [comment]
Hey, thanks for this great suggestion! One small issue is that I'm not sure how to properly go about it?

Just showing two pages on one screen (unless the image is horizontal) could work, but if the chapter contains a cover (like My Hero Academia), it wouldn't show it in the same manner as the book would, but instead "desynced" by one page. Perhaps I could make the first page always take up a whole "screen", but that might not be perfect.

**Comment by JipFr** [comment]
Check this out! https://github.com/AdollaApp/Adolla/commit/ed0063d1e991334eadd35c9476b18c3c1fd4376c

**Comment by yash-278** [comment]
Wow , it looks perfect. I think one last thing would be if pages can be displayed in descending order , since now it's like read Left page then right one. But the reading way is from RTL , so it's kinda weird to read if you get what I mean. I see you did flex there , probably just doing flex reverse might be the way to do it. Also just check if keyboard controls work in dual page layout , Forward is working fine just it doesn't go backward.

**Comment by JipFr** [comment]
Thanks! I didn't check keyboard controls, I'll fix it when I get the chance.

The screens _should_ be RTL, at least they are for me. Am I misunderstanding? https://streamable.com/npnccu

**Comment by yash-278** [comment]
Ahh , my bad. The screens _are_ RTL. I think I got confused somehow.

Thanks for the dual page feature , it's a lifesaver.

**Comment by JipFr** [comment]
Of course! Before closing, I'll have to fix it on vertical / non-wide screens, though

**Comment by JipFr** [comment]
Fixed!
