### ISSUE TITLE
[typo] Announcement date

### ISSUE THREAD

**Issue by Azique** [AdollaApp/Adolla#26]
Hi mate,

you have a typo in your announcements gist - it says 202**0**:
"On May 22 **2020**, The Creator said...

A new update is out. This update features an updated nhentai scraper, some bug fixes, and most importantly of all, the LONG AWAITED RETURN of MANGADEX including migration! Should something go wrong with migration, let me know."

and thank you for the update!

**Comment by JipFr** [comment]
Silly me, living in the past. I've fixed it now, thanks for reporting!
