### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by G-Rowell** [AdollaApp/Adolla#32]
Hi,

your repo here,

Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4

Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/Mango

They also have a GitHub org, where they likely also have some stolen work: https://github.com/tesseract-org.

Checkout their all their personal repos...

I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.

Galen

**Comment by JipFr** [comment]
Hey, thanks for sharing!

I've messaged the offender and they have made the repository private (hopefully they'll delete it) and will remove it from their site soon.

I'll wait with closing the issue until it is gone from their site as well.

**Comment by G-Rowell** [comment]
Yeah, they're certainly a serial offender as there are so many stolen & re-branded projects 😢 

Sorry again for the bad news,
all the best

**Comment by JipFr** [comment]
They have deleted / vandalised all their accounts, I consider this taken care of
