### ISSUE TITLE
Feature Request: Hide status bar when using reader in iPadOS PWA

### ISSUE THREAD

**Issue by kkanungo17** [AdollaApp/Adolla#42]
Is it possible to achieve this? I'd like to be able to use the full screen real estate.

**Comment by JipFr** [comment]
If you go into the reader settings and toggle setting "tap to toggle status bar" it will hide the status bar, but that's only really useful for long strips. Is that what you were looking for?

![image](https://user-images.githubusercontent.com/17685409/139527996-b649fe6c-0d80-4747-9a3c-e609712dcee5.jpeg)
![image](https://user-images.githubusercontent.com/17685409/139527986-f2eebc49-c151-4f33-a293-072a712b5c25.png)

**Comment by kkanungo17** [comment]
Ah yes, I use the iPad in landscape with book mode, so every pixel helps.
